name: se
channels:
  - conda-forge
  - defaults
dependencies:
  - datasets=2.9.0
  - jupyter=1.0.0
  - matplotlib=3.4.3
  - pandas=1.3.4
  - scikit-learn=0.24.2
  - seaborn=0.11.2
  - torch=1.13.1
  - tqdm=4.62.3
  - transformers=4.26.1
